#!/bin/sh
# -*- coding: utf-8 -*-
#
# ~/.xinitrc
#

# Executed by startx (run your window manager from here)
#xset s off

# no bell
xset -b

#(scale,tile,seemless,center)
#setxkbmap -option ctrl:swapcaps &
#autocutsel -selection CLIPBOARD -fork &
#autocutsel -selection PRIMARY -fork &

xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/TTF
xset fp rehash

# set the cursor
# xsetroot -cursor_name left_ptr

# background
# xsetroot -solid "#303030"
# feh --bg-scale ~/Downloads/118-e.jpg &
# feh --bg-tile ~/.xmonad/background.png &
# nitrogen --restore &
# `cat  $HOME/.fehbg`

# export OOO_FORCE_DESKTOP=gnome &
# xrandr --output default --mode 1440x900 --pos 0x0 &
# trayer --edge top --align right --SetDockType true --SetPartialStrut true \
#     --expand true --width 15 --height 12 --transparent true --tint 0x000000 &

# Fix Java GUIs
# wmname LG3D

# Load local modmap
test -r $HOME/.Xmodmap && xmodmap $HOME/.Xmodmap

# Load .Xdefaults
test -r $HOME/.Xresources && xrdb -merge $HOME/.Xresources
test -r $HOME/.Xdefaults && xrdb -merge $HOME/.Xdefaults

#[[ $(hostname) == "goudes" ]] &&
# source $HOME/dotfiles/config/autostart.sh

# Start agents
eval $(gpg-agent --daemon)
# eval `ssh-agent -s`
# eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)
