#!/bin/sh

# icons
ICONPATH=/home/phraok/.dzen/bitmaps
# network interface
INTERFACE=eth0
# update every x seconds
SLEEP=1

# Here we remember the previous rx/tx counts
RXB=`cat /sys/class/net/${INTERFACE}/statistics/rx_bytes`
TXB=`cat /sys/class/net/${INTERFACE}/statistics/tx_bytes`

while :; do

    # get new rx/tx counts
    RXBN=`cat /sys/class/net/${INTERFACE}/statistics/rx_bytes`
    TXBN=`cat /sys/class/net/${INTERFACE}/statistics/tx_bytes`

    # calculate the rates
    # format the values to 4 digit fields
    RXR=$(printf "%4d\n" $(echo "($RXBN - $RXB) / 1024/${SLEEP}" | bc ))
    TXR=$(printf "%4d\n" $(echo "($TXBN - $TXB) / 1024/${SLEEP}" | bc ))

    # print out the rates with some nice formatting
    echo "^fg(white)${RXR}kB/s^fg(#99CCFF)^p(3)^i(${ICONPATH}/arr_down.xbm)^fg(white)${TXR}  kB/s^fg(#99CCFF)^i(${ICONPATH}/arr_up.xbm)^fg()"

    # reset old rates
    RXB=$RXBN; TXB=$TXBN

    sleep $SLEEP
done | dzen2 -ta l -l 3 -u -fn '-*-terminus-*-r-normal-*-*-120-*-*-*-*-iso8859-*' -p -bg '#222222' -fg '#DDDDDD' -x 700 -y 0 -tw 150 -w 150 -sa c -e onstart=raise