export PATH=$PATH:~/.zsh/bin:~/bin:/usr/local/bin

#export LC_ALL="en_US.UTF-8"
#export LANG="en_US.UTF-8"

# Viewer/Editeur par defaut
export VISUAL=vim
export EDITOR="gvim -f"

if [ -x `which most` ]; then
   export PAGER=most
elif [ -x `which less` ]; then
   export PAGER=less
   export LESS="-ir"
   export LESSOPEN="| /usr/bin/lesspipe %s"
   export LESSCLOSE="/usr/bin/lesspipe %s %s"
fi

# Permissions rw-r--r-- pour les fichiers crées
# et rwxr-xr-x pour les répertoires crées
umask 022

# Proxy HTTP / FTP sans mot de passe
#export http_proxy="http://proxy.exemple.org:8080"
#export ftp_proxy="ftp://proxy.exemple.org:8080"

# Proxy HTTP / FTP avec mot de passe
#export http_proxy="http://login:password@proxy.exemple.org:8080"
#export ftp_proxy="ftp://login:password@proxy.exemple.org:8080"

# Ne pas passer par le proxy pour les domaines locaux
#export no_proxy="exemple.org"

# De la couleur pour grep
export GREP_OPTIONS='--color=auto'

export BROWSER="firefox -new-tab"
# run multiple Firefox
#export MOZ_NO_REMOTE=1

# repertoire texlive local
[ "$HOSTNAME" = "goudes" ] && MYTEXMF="miktex-texmf" || MYTEXMF=".texmf"
export TEXMFHOME=$HOME/$MYTEXMF

# turn off .lesshst file
export LESSHISTFILE="-"
